<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <material name="purple">
        <color rgba="0.5 0 0.5 1" />
    </material>
    <material name="red">
        <color rgba="1 0 0 1" />
    </material>
    
    <xacro:macro name="box_collition_inertia" params="m x y z o_xyz o_rpy">
        <collision>
            <geometry>
                <box size="${x} ${y} ${z}" />
            </geometry>
            <origin xyz="0 0 ${z / 2.0}" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia    ixx="${(m/12) * (y*y + z*z)}"   ixy="0"   ixz="0" 
                        iyy="${(m/12) * (x*x + z*z)}"   iyz="0" 
                        izz="${(m/12) * (x*x + y*y)}"   />
        </inertial>
        
    </xacro:macro>

    <xacro:macro name="cylinder_collition_inertia" params="m r l o_xyz o_rpy">
        <collision>
                <geometry>
                    <sphere radius="${r}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
        <inertial>
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia    ixx="${(1/12) * m * (3*r*r+l*l)}"   ixy="0"   ixz="0" 
                        iyy="${(1/12) * m * (3*r*r+l*l)}"   iyz="0" 
                        izz="${(1/12) *m*r*r}"   />
        </inertial>
        
    </xacro:macro>

    <xacro:macro name="sphere_collition_inertia" params="m r o_xyz o_rpy">
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia    ixx="${(2/5) * m * r*r}"   ixy="0"   ixz="0" 
                        iyy="${(2/5) * m * r*r}"   iyz="0" 
                        izz="${(2/5) * m * r*r}"   />
        </inertial>
        
    </xacro:macro>
</robot>